<rightbar>
	
		
		<h3>Friends</h3>
	<friends>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
	</friends>
		
		<h3>Sustainable Centers</h3>
	<scs>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
	</scs>
	
		<h3>Projects</h3>
	<projects>	
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
		<memberavatar></memberavatar>
	</projects>
</rightbar>